Implemented selected modpack header
Mystical-Machines/MM-Launcher pull request #6
Opened 2021-01-05 13:05 UTC by mattie078

app/landing.ejs - line 170
`					<pre style="text-align: center;white-space: normal;">
`

While it normally isn't good practice to have CSS in the style tag while having a CSS file. I still find it reasonable to exclude preformatted text. Due to the nature of that tag.

2021-01-05 15:16 UTC, Brend-Smits requested changes

2021-01-05 15:16 UTC, Brend-Smits commented on app/landing.ejs
> +						<button id="MM_server_selection_button">&#8226; No Server Selected</button>
No server or no modpack selected?

2021-01-05 15:16 UTC, Brend-Smits commented on app/landing.ejs
> +						<button id="MM_server_selection_button">&#8226; No Server Selected</button>
I would also prefer it if id's and classes were all lower case.

2021-02-14 16:04 UTC, mattie078 commented
Now that I finished my internship I will be having more time to also fix some issues with the current launcher.

2021-02-19 15:39 UTC, Brend-Smits commented
I will check this out today. Thanks for assigning me :)

2021-02-19 15:40 UTC, Brend-Smits commented
Please note that there is still a conflict.

2021-02-19 19:08 UTC, Brend-Smits approved these changes
Not tested, but I assume you did test it. Code looks great, thanks!

2021-02-22 12:43 UTC, merged